// <auto-generated />
using API_BLAZOR_;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_BLAZOR_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221004201708_Corrigindo banco")]
    partial class Corrigindobanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_BLAZOR_.Gerencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Gerencias");
                });

            modelBuilder.Entity("API_BLAZOR_.Gerente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GerenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GerenciaId")
                        .IsUnique();

                    b.ToTable("Gerentes");
                });

            modelBuilder.Entity("API_BLAZOR_.Gerente", b =>
                {
                    b.HasOne("API_BLAZOR_.Gerencia", "Gerencia")
                        .WithOne("Gerente")
                        .HasForeignKey("API_BLAZOR_.Gerente", "GerenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gerencia");
                });

            modelBuilder.Entity("API_BLAZOR_.Gerencia", b =>
                {
                    b.Navigation("Gerente");
                });
#pragma warning restore 612, 618
        }
    }
}
